### ISSUE TITLE
figure out deployment auth

### ISSUE THREAD

**Issue by lukewpatterson** [veewee-community/veewee-community.github.com#1]
# auth:

read - https://help.github.com/articles/managing-deploy-keys 
- ssh agent forwarding
  - nah, can't be automated
- oath
  - nah, applies to whole org
- deploy keys
  - nice that must have one deploy key per repo, minimize risk if key compromised
  - how to generate, how to hand off to travis?
- machine users
  - nah, don't want to manage all those dummy users

**Comment by lukewpatterson** [comment]
so go with deploy keys?

ok then, figure out how to create deploy keys - first, follow https://help.github.com/articles/managing-deploy-keys to https://help.github.com/articles/generating-ssh-keys

**Comment by lukewpatterson** [comment]
need to use [travis encryption keys](http://about.travis-ci.org/docs/user/encryption-keys/) to store private half of ssh key

can the private key fit in the payload travis gem can encrypt? no. [travis gem can encrypt](http://about.travis-ci.org/docs/user/encryption-keys/#Usage) 119 characters, and I clocked a sample private ssh key at 1766 characters.  ouch. need an intermediate step.

**Comment by lukewpatterson** [comment]
so, what, split up the key into 1766/119 different env vars. no, that is too cheesy even for me. or is it? hmm, it was just a joke but let me look into it.

**Comment by lukewpatterson** [comment]
before I forget, how to split key file into encrypted lines:

ENCRYPTION_FILTER="echo \$(echo \"-\")\$(travis encrypt veewee-community/veewee-push \"\$FILE='`cat $FILE`'\" | grep secure:)"
split --lines=1 --numeric-suffixes --suffix-length=2 --filter="$ENCRYPTION_FILTER" ~/.ssh/id_rsa id_rsa_

**Comment by jedi4ever** [comment]
An alternative could be to upload the file to temp like ftp server to incoming and have a process check the SHA1-checksum before uploading it an S3 bucket/dropbox ? It requires more bandwith but is maybe easier to setup?

**Comment by lukewpatterson** [comment]
@jedi4ever that might be the way to go.  If I can't get my current approach working soon, I'll look into what you suggest.

The thing that keeps drawing me to GitHub-hosting of binaries is the sustainability aspect.  Plus I don't want to hurt GitHub's feelings by turning down its gracious offer for free, stable and secure hosting :)

I think the deployment and auth issues might be a good investment now since the Travis queues aren't ready yet anyways.

**Comment by lukewpatterson** [comment]
Summary so far: publishing to the wiki was pretty much a bust.

**Notes:**
Things started off fine.  I [generated](https://help.github.com/articles/generating-ssh-keys) an [SSH _deploy key_](https://help.github.com/articles/managing-deploy-keys) and added it in the [veewee-push project's admin page](https://github.com/veewee-community/veewee-push/admin/keys).  The _deploy key_ is good for the main repo and the wiki repo, as evidenced by [successful "git push" attempt](https://travis-ci.org/veewee-community/veewee-push/builds/3559698/#L69)s.

I can even [push very large (e.g. 900mb) file](https://travis-ci.org/veewee-community/veewee-push/builds/3561032/#L71)s.  Notice how I have to ["git init" and force "push"](https://github.com/veewee-community/veewee-push/blob/486102e6f508214b04414074c921475e5943f682/.travis.yml#L13) every time to avoid bloating the wiki repo with version control deltas.  (I wanted to be careful not to creep towards [the 1GB storage limit](https://help.github.com/articles/what-is-my-disk-quota) over time.)

But it starts to fall apart: the URL structure for accessing raw data from the wiki repos doesn't appear to be stable.  Also, anything over about 100mb would only intermittently resolve when I accessed it directly from my browser.  And then there are [all the hoops I have to jump through](https://gist.github.com/4242707) with squeezing a private SSH key into the .travis.yml file.

**Comment by lukewpatterson** [comment]
... moving on to what appears to be a more practical and sustainable solution - use a [machine user](https://gist.github.com/4242707)'s [one-off OAuth token (recently created capability)](http://developer.github.com/changes/2012-12-06-create-authorization-for-app/), along with an [API library](http://developer.github.com/v3/libraries/), to upload to the Downloads section (discussed as "Packaged release versions", [here](https://help.github.com/articles/what-is-my-disk-quota)). ... more to come

**Comment by lukewpatterson** [comment]
@jedi4ever ok, some progress:

https://travis-ci.org/veewee-community/veeweebot/builds/3618753/#L29
shows the results of some work on the [deploy script](https://github.com/veewee-community/veeweebot/blob/156434c4ecae0820a87dccca57d1eabb0de405d5/deploy.sh) which is currently posting files to:
https://github.com/veewee-community/veeweebot/downloads

Searched and searched for a solution that didn't require writing any code, but couldn't find anything that would overwrite existing files of the same name when posting.

Will circle back around and document the admin side of this.  Will also test this out with larger files.

**Comment by lukewpatterson** [comment]
Ha!  This is classic:

https://github.com/blog/1302-goodbye-uploads

![image](https://f.cloud.github.com/assets/106582/7256/9f1cd3ea-43f9-11e2-9d9e-8a4a49ef4275.png)

**Comment by jedi4ever** [comment]
haha @lukewpatterson - what are the odds for that. Maybe they saw you uploading full files and got scared :)

**Comment by lukewpatterson** [comment]
I went back to the s3/dropbox/etc destinations you discussed earlier:
- S3 - had to rule it out because there is no rock-solid way to limit monthly bandwidth costs
  - https://forums.aws.amazon.com/message.jspa?messageID=152243
- Dropbox - can cap monthly costs, but don't see a clear way to publish directly from a script and end up with a "cURLable" link
  - https://www.dropbox.com/help/16/en
  - http://www.theverge.com/2012/6/15/3088865/dropbox-no-public-folder-new-users
- Google Drive - can cap monthly costs (which are [very reasonable](https://support.google.com/drive/bin/answer.py?hl=en&answer=2375123&topic=2375005&ctx=topic)) and can publish to a public folder
  - http://googleappsdeveloper.blogspot.com/2012/11/announcing-google-drive-site-publishing.html
  - https://developers.google.com/drive/publish-site

I went ahead and rewrote the deploy script to use Google Drive.

The script is here: https://github.com/veewee-community/veeweebot/blob/44cd4a0a61e7dd2e44f3e9f1231b1f9ebd727d4d/deploy.sh (you'll quickly realize that Ruby isn't my native language)

I'm having some trouble deploying >250MB files at the moment, the Travis box keeps running out of room, but it seems like something that could be fixed: https://travis-ci.org/veewee-community/veeweebot/builds

The Google Drive URLs aren't pretty, and they don't offer the ability to use a custom domain name (yet?), but if we want pretty URLs maybe something could be done with a simple HTTP redirect server sitting in front.

Here is the folder where my test runs are being deployed to: https://googledrive.com/host/0B6Yx_cuFmm6Mb1R1ZWdOUlhmWkE/

**Comment by lukewpatterson** [comment]
roadblock: https://groups.google.com/forum/?fromgroups=#!topic/travis-ci/x7WGHb89DlE

Travis must have switched to OpenVZ, can't load kernel modules anymore

**Comment by jedi4ever** [comment]
Don't think they'll change overnight without mentioning this.

Rather a coincidence that we got this error on Debian reported (similar)
https://github.com/jedi4ever/veewee/issues/451

Might just be mirrors down.

**Comment by jedi4ever** [comment]
If we can find a sponsor to host this, that would be less of a problem.

F.i. a machine on Hetzner for about 49Euro has a terrabyte download :)

**Comment by lukewpatterson** [comment]
Thanks I'll look into Hetzner to see what it has to offer.

For the Travis discussion, see travis-ci/travis-ci#811

**Comment by jedi4ever** [comment]
Here's what Hetzner Network pricing looks like:

*There are no charges for overage. We will permanently restrict the 
connection speed to 10 Mbit/s if more than 10,000 GB/month are used (the 
basis for calculation is for outgoing traffic only. Incoming and 
internal traffic is not calculated). 100 Mbit/s speed can be optionally 
restored by committing to pay 6,90 € (incl. VAT) per additional TB used. 
Please seehere for information 
http://wiki.hetzner.de/index.php/Bandbreitendrosselung_aufhebenon how 
to proceed.

If we find some sponsors - we can just buy a machine - (maybe from the 
auction)
https://robot.your-server.de/order/market
